# Generated by Django 5.2.1 on 2025-05-26 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128, verbose_name='Город')),
                ('city_lat', models.FloatField(null=True, verbose_name='Широта')),
                ('city_lon', models.FloatField(null=True, verbose_name='Долгота')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время запроса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос прогноза',
                'verbose_name_plural': 'Запросы прогноза',
                'ordering': ['-created_at'],
            },
        ),
    ]
